languageCode = "en-us"
title = "Aerial"
baseurl = "http://www.endtroduc.in/"
theme = "aerial"

[params]
  name = "endtroduc.in"
  about = "#java #dev #boot #cloud #agile #gamedev #pixelart #pico8"
  copyright = "edntroduc.in"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "a"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://www.twitter.com/KubaEndtroducin"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/jillukowicz"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:jakub.illukowicz@gmail.com"
